import { VerticalBox, LineEdit, Button } from "std-widgets.slint";

export component MainWindow inherits Window {
    width: 320px;
    height: 160px;
    title: "vrc_chat_bridge";

    in-out property <string> input_text: "";
    out property <int> input_length: input_text.character-count;

    callback submit(string);
    callback editing(string);

    public function focus_input() {
        input.focus();
    }

    VerticalBox {
        padding: 12px;
        spacing: 8px;

        input := LineEdit {
            text <=> root.input_text;
            placeholder-text: "文字を入力";

            edited(text) => {
                root.editing(text);
            }

            accepted(text) => {
                root.submit(text);
            }
        }

        Text {
            text: root.input_length + "/140";
        }

        Button {
            text: "送信";
            clicked => {
                root.submit(input_text);
            }
        }
    }
}

